# netlify.toml — Vite app at repo root
[build]
command = "npm ci && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# netlify.toml
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

