# netlify.toml — Vite app at repo root
[build]
command = "npm ci && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"

# SPA fallback
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
